matrix:
  allow_failures:
    - os: windows
  include:
    - os: osx
      osx_image: xcode9.4
      language: rust
      rust: nightly-2018-10-12
      env:
        - TRAVIS_NODE_VERSION="10"

    - os: linux
      language: rust
      rust: nightly-2018-10-12
      env:
        - TRAVIS_NODE_VERSION="10"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-multilib
            - g++-8
            - g++-multilib

    - os: windows
      language: node_js
      node_js:
        - node

    - os: windows
      language: rust
      rust: nightly-2018-10-12
      env:
        - TRAVIS_NODE_VERSION="10"

cache:
  yarn: true
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-8"; fi
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use ${TRAVIS_NODE_VERSION}
  - node -v
  - npm -v
  - npm i -g yarn@latest

install:
  - yarn

script:
  - yarn build
  - yarn test
